# Generated by Django 3.1.1 on 2020-12-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('rut', models.FloatField(blank=True, null=True)),
                ('digv', models.CharField(blank=True, max_length=1, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.FloatField(blank=True, null=True)),
                ('activo', models.FloatField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('is_rol', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.FloatField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('area_actuacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id_funcion', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('usuario_id_usuario', models.FloatField()),
            ],
            options={
                'db_table': 'funcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FunProc',
            fields=[
                ('id_fun_proc', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fun_proc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistRep',
            fields=[
                ('id_hist_rep', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('archivo', models.TextField(blank=True, null=True)),
                ('usuario_id_usuario', models.FloatField()),
            ],
            options={
                'db_table': 'hist_rep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistTar',
            fields=[
                ('id_hist_tar', models.FloatField(primary_key=True, serialize=False)),
                ('estado_inicial', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_final', models.CharField(blank=True, max_length=50, null=True)),
                ('nota', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'hist_tar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id_proceso', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id_subtarea', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('finalizado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'subtarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('encargado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'unidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuTar',
            fields=[
                ('id_usu_tar', models.FloatField(primary_key=True, serialize=False)),
                ('usuario_id_usuario', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usu_tar',
                'managed': False,
            },
        ),
    ]
