# Generated by Django 3.1.1 on 2020-12-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201213_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
