# Generated by Django 3.1.1 on 2020-12-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False},
        ),
    ]
