# Generated by Django 3.1.1 on 2020-12-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201213_0103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
    ]
