# Generated by Django 3.1.1 on 2020-12-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201213_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_rol',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_usuario',
            field=models.FloatField(default=False),
        ),
    ]
